server:
  port: 11000

spring:
  application:
    name: upload

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

fdfs:
  so-timeout: 1501 # 读取文件超时时间
  connect-timeout: 601 # 连接服务器超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122），只会在工程启动的时候连接FastDfs服务器，所以必须保证FastDfs服务器在工程之前启动
    - 192.168.192.129:22122
