server:
  port: 10001

spring:
  application:
    name: item
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/leyou
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level.com.leyou.item: debug


mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.leyou.item.pojo