server:
  port: 9199

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  application:
    name: goods
  rabbitmq:
    host: localhost
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

